music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :bands
  resource :session, only: [:new, :create, :destroy]
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password
  
  after_initialize :ensure_session_token
  
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :show
  end

  def create
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :index
  end

  def update
  end

  def destroy
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user.nil?
      flash.now[:errors] = ["Incorrect email or password."]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(id: user.id)
    end
  end
  
  def destroy
    log_out_user!
    redirect_to new_session_url
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token'
      value='#{form_authenticity_token}' />".html_safe
  end
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h1>Music App</h1>

    <section>
      <% if current_user.nil? %>
        <a href="<%= new_session_url %>">Sign in</a>
        <a href="<%= new_user_url %>">Sign up</a>
      <% else %>
        <%= current_user.email %>
        <form action="<%= session_url %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
        </form>
      <% end %>
    </section>
  </header>

  <body>
    
    <%= yield %>
  </body>
</html>

music_app/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

music_app/app/views/users/new.html.erb
<section>
  <h2>New User</h2>

  <%= render "shared/errors" %>

  <form action="<%= users_url %>" method="post">
    <%= auth_token %>

    <label for="email">Email 
    <input
      type="text"
      name="user[email]"
      id="email">
    </label>
      
    <br>

    <label for="password">Password 
    <input
      type="text"
      name="user[password]"
      id="password">
    </label>

    <br>

    <input type="submit" value="Sign up">
  </form>
</section>

music_app/app/views/users/show.html.erb
<section>
  <h2>Welcome, <%= @user.email %>!</h2>
</section>